### ISSUE TITLE
 prediction not maintaining the input resolution 

### ISSUE THREAD

**Issue by akshay9396** [guglielmocamporese/hands-segmentation-pytorch#11]
Hello,
After running the main.py with predict, I've encountered a new problem where it produces an additional image with a black mask.

Could you kindly provide guidance on any additional steps or configurations necessary to ensure that the script generates the outputs accurately?

Sure, I'll be happy to give a star to the project repo. Keep up the great work!

Thank you once again for your invaluable support. Your assistance in resolving this matter would be immensely appreciated.

**Comment by guglielmocamporese** [comment]
Fixed.

The issue is not related to the prediction resolution, this is maintained - I just double-checked. The issue was related to the fact that you were feeding back to the model the predictions, and in this way, some of the outputs were completely black. I fixed this problem by adding a postfix to the prediction so that in case you recompute the output, the old predictions are filtered out.

Best,
Guglielmo
